title: Mapping Fast Disaster
description: UCI Anthro 25A 

url: https://timschuetz.github.io/fast-disaster
baseurl: "/long-haul"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: RMP Facilities
   url: /rmp
 - title: Ammonium Nitrate
   url: /ammonium-nitrate
 - title: About
   url: /about

social:
   github: tmschtz
   twitter: enviroinjustice
   facebook: 
   email: tschuetz@uci.edu

google_analytics: "UA-58263416-1"
